version: '3'
services:
  postgres:
    image: postgres:16
    container_name: animales-db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: animalesDB
    volumes:
      - animales-pg-data:/var/lib/postgresql/data
volumes:
  animales-pg-data:
